title: Services

pages:
  template: service
  sort: flip
  num: date

options: 
  template: false
  status: false

icon: newspaper-o

fields:
  title:
    label: Title
    type: title
    required: true
    width: 3/4

  info:
    label: Hint
    type: info
    text: >
      Djelatnosti
